overrides:
  '@babel/helpers@<7.26.10': '>=7.26.10'
  '@babel/traverse@<7.23.2': '>=7.23.2'
  '@octokit/plugin-paginate-rest@>=1.0.0 <9.2.2': '>=9.2.2'
  '@octokit/request-error@>=1.0.0 <5.1.1': '>=5.1.1'
  '@octokit/request@>=1.0.0 <8.4.1': '>=8.4.1'
  ajv@<6.14.0: '>=6.14.0'
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  braces@<3.0.3: '>=3.0.3'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  diff@>=4.0.0 <4.0.4: '>=4.0.4'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  micromatch@<4.0.8: '>=4.0.8'
  minimatch@<3.1.3: '>=3.1.3'
  semver@>=7.0.0 <7.5.2: '>=7.5.2'
  tmp@<=0.2.3: '>=0.2.4'
